version: "3"
services:
  application:
    build: .
    command: npm start
    environment:
      - DATABASE_HOSTNAME=mongodb
    depends_on:
      - mongo
    volumes:
      - ./:/data
    ports:
      - '8080:8080'
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'