version: '3'
services:
  search:
    build: .
    depends_on:
      - search_elasticsearch
      - search_rabbitmq
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8007:8007'
  search_elasticsearch:
    image: elasticsearch:8.6.0
    restart: on-failure
    ports:
      - '9200:9200'
  search_rabbitmq:
    image: rabbitmq:latest
    restart: on-failure
    ports:
      - '5672:5672'