version: '3'
services:
  cart:
    build: .
    depends_on:
      - cart_redis
    environment:
      - REDIS_HOSTNAME=redis
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8003:8003'
  cart_redis:
    image: redis:latest
    restart: on-failure
    ports:
      - '6379:6379'