version: '3'
services:
  profile:
    build: .
    depends_on:
      - profile_mongo
    environment:
      - MONGO_HOSTNAME=mongodb
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8008:8008'
  profile_mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'