version: '3'
services:
  catalog:
    build: .
    depends_on:
      - catalog_mongo
      - catalog_rabbitmq
    environment:
      - MONGO_HOSTNAME=mongodb
      - RABBITMQ_HOSTNAME=rabbitmq
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8002:8002'
  catalog_mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'
  catalog_rabbitmq:
    image: rabbitmq:latest
    restart: on-failure
    ports:
      - '5672:5672'