version: "3"
services:
  catalog:
    build: .
    command: npm start
    restart: always
    environment:
      - DATABASE_HOSTNAME=mongodb
    ports:
      - "8002:8002"
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'