version: '3'
services:
  confirmation:
    build: .
    depends_on:
      - confirmation_redis
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8083:8083'
  confirmation_redis:
    image: redis:latest
    restart: on-failure
    ports:
      - '6379:6379'