services:
  application:
    build: .
    depends_on:
      - mongo
    volumes:
      - ./:/data
    restart: always
    ports:
      - '8082:8082'
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'