version: "3"
services:
  stock:
    build: .
    command: npm start
    restart: always
    environment:
      - DATABASE_HOSTNAME=mongodb
    ports:
      - "8081:8081"
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'