version: "3"
services:
  application:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_HOSTNAME=mongodb
    volumes:
      - ./:/data
    restart: always
    ports:
      - '8001:8001'
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'