version: '3'
services:
  category:
    build: .
    depends_on:
      - category_mongo
    environment:
      - MONGO_HOSTNAME=mongodb
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8001:8001'
  category_mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'