version: '3'
services:
  promo:
    build: .
    depends_on:
      - promo_redis
    environment:
      - REDIS_HOSTNAME=redis
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8009:8009'
  promo_redis:
    image: redis:latest
    restart: on-failure
    ports:
      - '6379:6379'