version: '3'
services:
  delivery:
    build: .
    depends_on:
      - delivery_mongo
    environment:
      - MONGO_HOSTNAME=mongodb
    volumes:
      - ./:/data
    restart: on-failure
    ports:
      - '8005:8005'
  delivery_mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'