version: "3"
services:
  stock:
    build: .
    command: npm start
    restart: always
    environment:
      - DATABASE_HOSTNAME=mongodb
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'